spring:
  application:
    name: user-ms
  profiles:
    active: docker

  config:
    import: configserver:http://config-server:8888

  # Configuración de seguridad OAuth2 para Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/proyect-ms-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:9989/eureka/
