@host=http://localhost:8082

###
GET {{host}}/carrito-compra/list-items-carrito/1



###
DELETE {{host}}/carrito-compra/delete-item-carrito?uid=1&itemId=1

###
PUT {{host}}/carrito-compra/agregar-item-carrito?uid=1
Content-Type: application/json

{
  "id": 1,
  "idItem": 101,
  "cantidad": 2,
  "precioUnitario": 100.00,
  "nombreItem": "Test Item"
}

###
GET {{host}}/actuator/info