@host=http://localhost:8082

GET {{host}}/transaccion/list/1

###
POST {{host}}/transaccion/create/1
Content-Type: application/json

[102]

###
POST {{host}}/transaccion/process-payment/1

###
GET {{host}}/actuator/info